### ISSUE TITLE
Remove PySide override on Linux platforms in "master"!

### ISSUE THREAD

**Issue by Aranuvir** [makehumancommunity/makehuman#1]
Due to the fact that Linux still supports PyQT4 very well and PySide created an error I wasn't able to solve, I decided to override PySide checking for Linux platforms on my branch. This has recently be merged to master and should be removed if we have finally decided on the platform.

File affected:
makehuman/lib/core.py: line 41 and line 53

**Comment by joepal1976** [comment]
Ok, I'll revert it tomorrow. I'm too tired now to be sure what I'm doing.

**Comment by Aranuvir** [comment]
Leaving this issue open, since it will be reintroduced from time to time. Until those severe bugs with Pyside aren't fixed, I'm not going to remove the code from my branch. This issue should be closed before release...

**Comment by joepal1976** [comment]
Closing this now after the Qt5 changes have been merged. The master branch no longer contains any trace of pyside.
