### ISSUE TITLE
QDialogs open a second time

### ISSUE THREAD

**Issue by Aranuvir** [makehumancommunity/makehuman#10]
If QFileDialog is called or a prompt is opened, after closing the dialog the same dialog opens a second time. This happens on Linux as well as on Windows (tested here with PyQt5 5.10).

**Comment by joepal1976** [comment]
I think this is fixed by https://github.com/makehumancommunity/makehuman/commit/9e334c40780bec8f05a1cd19ec0e4b5fe23e7114, but it needs to be tested.

**Comment by Aranuvir** [comment]
The bug was copied to the new tracker. I consider it fixed, anyway.
