### ISSUE TITLE
Add Contribution Guide

### ISSUE THREAD

**Issue by Zenahr** [makehumancommunity/makehuman#101]
Having a Contribution Guide (or at least an intro for it) on the readme would enable more users to jump into contribution more easily.

For example: I don't know at first glance if I'd be able to support the project by providing art-assets as a 3d-artist.

If there is a contribution guide which I just so happen to not find then I'd be awesome to have linked on the readme.

**Comment by Aranuvir** [comment]
http://www.makehumancommunity.org/content/user_contributed_assets.html

**Comment by joepal1976** [comment]
@Zenahr Yes, we're behind on lots of the documentation, including introductory guides on content creation aimed at artists.

**Comment by Zenahr** [comment]
I'll be glad to help out with that.

**Comment by joepal1976** [comment]
In general, this is what we have the wiki for: http://www.makehumancommunity.org/wiki/Main_Page

There are major sections of the wiki which could benefit from an overhaul, and several sections which could/should be added.
