### ISSUE TITLE
Save model UI might be confusing

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/makehuman#107]
Right now, there's a box called "name" in the left margin. If you fill that out and click "save" nothing happens. This is because the _file_ name is supposed to be entered in the unlabelled input box in the main widget, while the "name" box is the metadata string that ends up inside the saved file.

This is not immediately apparent to new users. 

We should at least have a message box about needing to enter a file name if none has been entered when clicking the save button.

**Comment by Aranuvir** [comment]
Make one big group box to the left & call it metadata. Perhaps add another label where to enter the filename. Not sure if that's really a problem...

**Comment by Aranuvir** [comment]
I've revised the task views. Hopefully everyone is happy, now...

**Comment by Aranuvir** [comment]
Everyone is screaming with enthusiasm... :)
