### ISSUE TITLE
Multiple Row Selection for Community Assets

### ISSUE THREAD

**Issue by christopwner** [makehumancommunity/makehuman#110]
Please allow multiple row selection in the community asset page for downloading multiple items at a time.

Release HEAD b32df8df (202000705 i think)

**Comment by Aranuvir** [comment]
Despite the fact that this is the wrong repo to report, there were reasons due to limited traffic and bandwidth of the server...

**Comment by christopwner** [comment]
understood, i'll move to the appropriate repo
