### ISSUE TITLE
Community Asset Filter for Already Downloaded requires Restart

### ISSUE THREAD

**Issue by christopwner** [makehumancommunity/makehuman#111]
The filter `Already downloaded` in the Community Asset tab requires a restart of MakeHuman to determine which assets have been already downloaded. I would assume this should work after each `Update list` button press.

Using nightly build: HEAD b32df8df

**Comment by Aranuvir** [comment]
Please report to the appropriate repo: https://github.com/makehumancommunity/community-plugins-assetdownload

**Comment by christopwner** [comment]
will do; didn't realize they were seperate repos
