### ISSUE TITLE
Makehuman doesn't open mhm file

### ISSUE THREAD

**Issue by Luca-lu-barista** [makehumancommunity/makehuman#112]
after saving my file (default is mhm), i can't open it anymore..

**Comment by Aranuvir** [comment]
With this extremely scarce amount of information we are definitely unable to help here. In general loading files works and was tested for probably more than a decade now, so most likely not a bug. Maybe you wanna ask for help in the forum?

**Comment by joepal1976** [comment]
This is the third report I've gotten regarding not being able to open MHM file, all within the last two weeks. 

That's at least one too many to be random.

But as aranuvir says, we're a bit short on information. Please go through the process one more time (try to save a file and then do whatever you can to open it, even if it doesn't work), and then post the log files here. 

You can find information on how to find logs here: http://www.makehumancommunity.org/wiki/FAQ:How_to_provide_a_makehuman_log_for_a_good_bug_report%3F

Per reference, the previous person I talked with didn't have anything strange on their machine (such as an odd system encoding), and we could never find out what was wrong. But after having reinstalled makehuman it started to work.

**Comment by Aranuvir** [comment]
I suppose most users are struggling with the concept of changing the working directory and selecting files. 
Suggesting to set the criticalness to low as long as we do not get minimum more of information than "it does not work".

**Comment by Aranuvir** [comment]
No further information here. Does the problem still exist?

**Comment by Aranuvir** [comment]
Seems to be solved.
