### ISSUE TITLE
Viewport not visible

### ISSUE THREAD

**Issue by jarinox** [makehumancommunity/makehuman#113]
When running makehuman on Arch Linux the viewport doesn't appear. However the tab menu and open/save/... buttons are visible - you can even successfully take a screenshot which shows the model that was opened.
This happens when cloning and running makehuman from Github as well as when running the version from the Arch User Repository.
![makehuman](https://user-images.githubusercontent.com/45308098/87586324-aa476100-c6e0-11ea-9e34-ddd9afe40eaf.png)

**Comment by Aranuvir** [comment]
Looks like #46... Try the --noshaders option...

**Comment by joepal1976** [comment]
For reference, there is now also this: http://www.makehumancommunity.org/wiki/FAQ:The_interface_looks_broken
