### ISSUE TITLE
Startup failure.

### ISSUE THREAD

**Issue by e-setup** [makehumancommunity/makehuman#118]
When I startup makehuman from a clean installation, it works fine. But after the first run, means there're files generated by MH in a folder name "v1py3" in my document folder, it starts to fail, generating the follow error log.
I'm using MH1.2 pre-release in windows 10 home, GBK encoding.
----------------------------------------------
error: 'gbk' codec can't decode byte 0xa2 in position 1095: illegal multibyte sequence
Traceback (most recent call last):
  File "makehuman.py", line 582, in main
    init_logging()
  File "makehuman.py", line 198, in init_logging
    import log
  File "./lib\log.py", line 49, in <module>
    from core import G
  File "./lib\core.py", line 80, in <module>
    G = Globals()
  File "./lib\core.py", line 58, in __init__
    self._preStartupConfigScan()
  File "./lib\core.py", line 67, in _preStartupConfigScan
    data = json.load(f)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 293, in load
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 1095: illegal multibyte sequence

**Comment by Aranuvir** [comment]
I'm not sure but this could be really a problem we have to address. From the Python 3.8.2 documentation:
>In text mode, if encoding is not specified the encoding used is platform dependent: locale.getpreferredencoding(False) is called to get the current locale encoding.

I thought it would default to utf-8 in the case encoding is not specified, or maybe there was a change in that behavior. We should consider to force encoding=utf-8 to all open() calls. Perhaps it fixes the issue. Setting the priority to urgent atm.

**Comment by Aranuvir** [comment]
I've created a a new branch _feature_fix_io_encoding, addressing the encoding problem and fixing a bunch of other problems. The plug-ins must be checked one by one ...

**Comment by e-setup** [comment]
I've done some test, problem solved.

**Comment by Aranuvir** [comment]
Thank you for your feedback. Could you give us some further information, what fixed your problem? It would be quite helpful for the project.

**Comment by rwbaer** [comment]
Has the "fix exists" code long since been rolled into master, or if not, should it be? Just noticing that this has an "urgent tag" and yet it is still open.

**Comment by rwbaer** [comment]
Didn't mean to close, just to comment.

**Comment by Aranuvir** [comment]
It is/was open because the situation is still not save and I had in mind to replace the read functions. As long as we write and read the data only from inside MakeHuman with a balanced "encoding='utf-8'" everything will be fine. But as soon as you forget the encoding or data is edited outside MakeHuman without ensuring the usage of utf-8 the application will crash.
(See also my "internal" post  2020-12-21). We can leave it closed, it was just a reminder.
