### ISSUE TITLE
Can't find plugin after reinstalled Blender

### ISSUE THREAD

**Issue by rico345100** [makehumancommunity/makehuman#12]
After I reinstalled Blender, plugin files are located properly but Blender can't read it. I try to install manually, but there are too many scripts and I don't know which one to load.

Make a zip file and load also doesn't worked, and re-download import plugin and paste all doesn't worked either.

How do I fix this?

Also I can't sign up official website of make human. Please fix it.

**Comment by Aranuvir** [comment]
Based on the number of spammers we have to purge everyday, generally registration in the forums  seems to work quite well. Please retry: http://www.makehumancommunity.org/forum/ucp.php?mode=register
