### ISSUE TITLE
Viewport is not working in ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by rokib-rajon** [makehumancommunity/makehuman#120]
![Screenshot_2020-08-10_23-07-28](https://user-images.githubusercontent.com/55991864/89810113-5ce2d600-db5e-11ea-8f90-64ce60959261.png)
After opening the pre-release program, the viewport is not showing up. It shows only wallpaper of the laptop,

**Comment by Aranuvir** [comment]
I think we had that issue report multiple times, now. Please try noshader/nosamplebuffer in the settings. Should fix your problem (partially).
If it doesn't help, the issue can be reopened again...
