### ISSUE TITLE
Modesty addon

### ISSUE THREAD

**Issue by DonFlymoor** [makehumancommunity/makehuman#121]
## Problem
Makehuman is a very useful program for creating characters, but is lacking in modesty. Some people may be bothered by that, and having a modesty addon could grow the community.
## Solution
Create an addon, enabled by default, which uses a "modest" skin pack and disables some setting which lack modesty. If anyone is intrested in creating such an addon and implementing it in the default makehuman program, I have a modified skin texture pack which I can upload.

Here is what the a "modest" character could look like
Male:
![image](https://user-images.githubusercontent.com/36929174/90673176-5838b480-e225-11ea-8c9b-38e7c3cfa6c1.png)
Female:
![image](https://user-images.githubusercontent.com/36929174/90673281-828a7200-e225-11ea-9307-e2a7cf744133.png)

**Comment by Aranuvir** [comment]
Just set it to enhancement request, since it is not a bug. That does not necessarily mean the function will ever come. Priority (very) low. Further discussion is needed...

**Comment by Aranuvir** [comment]
Since no one else has commented on that subject for more than a month, I consider it rejected. Could be reopened by the admins.
