### ISSUE TITLE
python TypeError when running download_assets_git.py

### ISSUE THREAD

**Issue by fevernight** [makehumancommunity/makehuman#122]
I cloned the main branch of the repo, installed dependencies as per Readme and configured git to use LFS.
Everything went smoothly until I got an error when running the download_assets_git.py:
`Traceback (most recent call last):
  File "download_assets_git.py", line 180, in <module>
    DownloadAssetsGit()
  File "download_assets_git.py", line 102, in __init__
    gitutils.cloneRepo(self._git_official_assets_repo,self._git_official_clone_location,self._git_official_assets_branch,extraargs=['--depth=1'])
  File "./lib/gitutils.py", line 260, in cloneRepo
    subprocess.check_call(args)
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1637, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not list
`
I used python3 download_assets_git.py
Reading the error I was able to interpret the problem and made a small change to the script:
changed line 102 from
` gitutils.cloneRepo(self._git_official_assets_repo,self._git_official_clone_location,self._git_official_assets_branch,extraargs=['--depth=1'])`
to
`gitutils.cloneRepo(self._git_official_assets_repo,self._git_official_clone_location,self._git_official_assets_branch,extraargs='--depth=1')`

After that, I was able to complete installation and run makehuman succesfully with all the default assets.

**Comment by Aranuvir** [comment]
Thank you for reporting the bug and providing a solution. If there are more than one extraargs, it might be more convenient providing a list of strings, so my solution checks if extraargs is a list and converts it do a string if necessary. Can you check if your issue gets fixed by my solution?

**Comment by Aranuvir** [comment]
Thank you again for testing :)
