### ISSUE TITLE
Widget on long panes get compressed when scrolled down

### ISSUE THREAD

**Issue by bodqhrohro** [makehumancommunity/makehuman#123]
I first thought it's a feature, but in this long list they get a zero height.
![makehuman_bug1](https://user-images.githubusercontent.com/2134486/91978277-8392c780-ed2c-11ea-861f-288370acaad9.gif)

Can be reproduced with the default theme as well.

MakeHuman Community 1.2.0-beta2 on Debian Bullseye, Qt 5.14.2.

**Comment by Aranuvir** [comment]
We are aware of that problem #77. The problem arises with newer versions of Qt. Current solution: downgrade Qt...
