### ISSUE TITLE
Scroll bars of properties and options scale content

### ISSUE THREAD

**Issue by TheJackiMonster** [makehumancommunity/makehuman#126]
Against expectations the scroll bars stretch and scale vertically all the options/widgets their boxes contain instead of scroll through them.

This happens in the 1.2.0 beta2, built on Arch Linux but I would assume this is a general bug from connecting wrong properties in Qt to the slider. 

![Peek 2020-09-26 21-22](https://user-images.githubusercontent.com/13867397/94348921-7e315000-0040-11eb-91c2-8632a66326ee.gif)

**Comment by Aranuvir** [comment]
We had that report multiple times, now. Current workaround: downgrade pyqt...
