### ISSUE TITLE
Full exit crash if bundled python is blocked by firewall when downloading from community list

### ISSUE THREAD

**Issue by Hunanbean** [makehumancommunity/makehuman#127]
Not sure if this belongs here, or under sockets.
Crashed by doing this:
having firewall rules not set for bundled python, or set to block, in 'simplewall' firewall software
Go to community tab and selecting clothes (probably any would do the same)
Click Update List
select an item and press download
MakeHuman does a full exit crash as the firewalls permission windows pops up, or if the bundled python is on the block list

**Comment by joepal1976** [comment]
Thanks. That sounds like a scenario we haven't tested for. 

I'm going to close this issue in favor of a copy I've placed in the asset downloader tracker: https://github.com/makehumancommunity/community-plugins-assetdownload/issues/33
