### ISSUE TITLE
Im trying to make an accouunt bot HOLY SH*T

### ISSUE THREAD

**Issue by Darkolen** [makehumancommunity/makehuman#132]
![bandicam 2020-10-24 20-18-03-472](https://user-images.githubusercontent.com/69396886/97096155-0ef64e00-1636-11eb-81c6-5adafaf9f6c6.jpg)
Now, How, What, When who, why do I need to doo all of these,,,, I don't even know what these are!, may you help me... i REALLY wanted to make an makehuman account

**Comment by Loki1950** [comment]
Hi Darkolen notice that there are no * next to any of the slots you showed just leave them blank we really only need a username and the e-mail address that goes with it :) the rest is just a few of the instant messenger services available while "Location,Occupation,Interests" are there as quick things about you that other forum members may associate to you and BTW feel free to ask those newbie questions we don't bite ;)
Enjoy the Choice :)

**Comment by Darkolen** [comment]
But when I tried/ they said. something wasn't signed in. first allow me to try again

**Comment by Aranuvir** [comment]
Not a bug.

**Comment by joepal1976** [comment]
If it asks you to enter a captcha, the response is "namuhekam". If the problem is that you never got an activation email, please enter what username you used when registering and I'll take a look at it.
