### ISSUE TITLE
Is this a known Bug?

### ISSUE THREAD

**Issue by Darkolen** [makehumancommunity/makehuman#135]
when I make a FBX, of my mak human model I always get BLACK EYES. is there anyway around this?
![bandicam 2020-10-27 20-53-10-454](https://user-images.githubusercontent.com/69396886/97377446-714d8980-1896-11eb-90ba-9861e9258c05.jpg)

also, I do get the eyelashes that arent like rendered as well. Pls asnwer

I won't be able to come back because My electronics get suspended

**Comment by chriku** [comment]
The Hair also has rectangular tips, while they should be "sharp". You are missing the alpha channel, so all transparent parts (Hair tips, Eye-Lash-Lashes and the outer eye bubble) are rendered as opaque (in your case) black geometry.

**Comment by Darkolen** [comment]
I thank You, good sir or ma'am I want to move this to makehuman, so I could get a guide on how to do this
