### ISSUE TITLE
Corrupt windows archive for version 1.2.0

### ISSUE THREAD

**Issue by gebeleizis** [makehumancommunity/makehuman#140]
The archive for windows version 1.2.0 is corrupt. At least, this is what happened in my case. Thank you very much in advance!

**Comment by joepal1976** [comment]
The windows file works when I test it now, and has been downloaded a couple of thousand times now. I would guess you either tried to double-click the installer without first extracting it from the zip file, or that you ran into a problem while downloading the file.

In the later case: If you download it again, you can check if the file got through intact by comparing its md5sum to the number listed here: http://download.tuxfamily.org/makehuman/releases/md5sums.txt

On windows you can either download a utility for checking md5sums, or use the build-in tool described here: https://onthefencedevelopment.com/2017/08/15/windows-10-builtin-md5-checksum-calculator/

**Comment by Aranuvir** [comment]
I guess we can close the issue.
