### ISSUE TITLE
Blender's Makehumans missing materials/ Uv shaders

### ISSUE THREAD

**Issue by Fakey-Person** [makehumancommunity/makehuman#142]
![bandicam 2020-11-29 15-54-11-786](https://user-images.githubusercontent.com/75279474/100668151-7ab09280-3329-11eb-88bf-a84ed890ac6e.png)
 I had many people in my scene in Blender, and some of them were all white, I then check there Uv and shaders.... They didn't have any.
The white/no shader 
![bandicam 2020-11-30 16-38-03-051](https://user-images.githubusercontent.com/75279474/100668792-79cc3080-332a-11eb-8706-aab03bbd3d69.png)
another person with all the shaders and Uvs
![bandicam 2020-11-30 16-38-09-611](https://user-images.githubusercontent.com/75279474/100668934-a97b3880-332a-11eb-8ae7-b6e3c3424dab.png)

**Comment by Fakey-Person** [comment]
c: Low

**Comment by Aranuvir** [comment]
Not very informative, although there are some pictures. One has to make many guesses what the OP is doing here. Since the issue seems to occur randomly best changes are it's this bug:  https://github.com/makehumancommunity/makehuman-plugin-for-blender/issues/55. Can you confirm this is a duplicate?

**Comment by Fakey-Person** [comment]
OK the other UV image is another make a human model with her denim jacket

**Comment by Fakey-Person** [comment]
OK we may have the same issue, but it was different causes, I have any other humans which are not textures or all white

**Comment by Fakey-Person** [comment]
ok THIS  Is kinda annoying, this is basically saying is you can't you're Makehuman models as filler or have more than with the same skin. this is angering me, this may be a Bug, That happens ALl the time. NO MATTER if you put ON, it will lead to the same way. so IN YOUR SCENES, YOU CAN ONLY USE ONE OF THE SAME SKIN ONCE OR MORE
![bandicam 2020-12-05 05-35-54-063](https://user-images.githubusercontent.com/75279474/101240227-e5f8bc80-36bb-11eb-8dc0-107122560cb3.png)
![bandicam 2020-12-05 05-36-15-576](https://user-images.githubusercontent.com/75279474/101240228-e6915300-36bb-11eb-966c-3a0fd904521a.png)
![bandicam 2020-12-05 05-36-37-427](https://user-images.githubusercontent.com/75279474/101240229-e729e980-36bb-11eb-987b-13347b50372f.png)

and if it is just me, I feel attacked, My laptop is pretty decent, so I dare you

P.S this ruined like 3 of my scenes because this BUG.

**Comment by Aranuvir** [comment]
Obviously wrong bug tracker. Closing.

**Comment by Fakey-Person** [comment]
> Obviously wrong bug tracker. Closing.

what do you mean?

**Comment by Fakey-Person** [comment]
and how will I so-called find the "right bug tracker". 
(crapping on noobs, is a sure way on how to boost your site/ application, Keep it, and you will be sure to FAIL, cant at least help, jeez, this is why you need one nice moderator and one strict moderator)

**Comment by joepal1976** [comment]
There is a similar issue previously reported here: https://github.com/makehumancommunity/makehuman/issues/142#issuecomment-739330783

A few comments up we asked if you could check that issue and confirm whether it is the same issue that you are having.

That issue is posted on the MPFB bug tracker, i.e the bug tracker for the blender plugin. The bug tracker we're writing in at the moment is the bug tracker for the MakeHuman application as such.

**Comment by Fakey-Person** [comment]
sorry for the outrage before, I had a sh*tty day that day, this tipped me over
anyway, I ah..................................................................................................................... I see Ima FFFFFFFF*uckig idiot. i guess I miss clicked before
want me to move it........... yeah  I don't deserve it

**Comment by Fakey-Person** [comment]
Since I'm such a f*aggot. I'll annoy my boy HH to  make an account, he sees to handle things better than me
