### ISSUE TITLE
can not open makekhuman

### ISSUE THREAD

**Issue by coco79** [makehumancommunity/makehuman#144]
hi!
under window 10 I download makehuman 1.2
I install it
from the icon on the desktop i can not get it running
window 10 said, pythonw.exe bloqued for security reason
Thank you for your help

**Comment by joepal1976** [comment]
This is something caused by your antivirus or firewall settings. There is nothing much we can do about that from our side.

**Comment by Aranuvir** [comment]
There is a good solution for that problem: https://www.linux.org/pages/download/ (Just download and install) :grin:. Though, this solution might not be applicable for everyone...
