### ISSUE TITLE
Viewport sucks

### ISSUE THREAD

**Issue by Pymann** [makehumancommunity/makehuman#154]
I attached a screenshot, that shows the viewpoer of the program does not work, I dont know if its related to ubuntu 20.04. I saw more problems with it
![Screenshot from 2021-02-12 21-46-11](https://user-images.githubusercontent.com/18898408/107820894-deb8f380-6d7b-11eb-8ddf-5a676ff0d516.png)

**Comment by Aranuvir** [comment]
Perhaps it's possible to find a more meaningful heading for that problem. Since we are aware of that problem and the bug report is a duplicate, I'm going to close i in favor of other bug reports.

**Comment by joepal1976** [comment]
Possibly the FAQ sucks too... https://github.com/makehumancommunity/makehuman/issues/154
