### ISSUE TITLE
Make up a body shape from the physical measurements of a person

### ISSUE THREAD

**Issue by goatchurchprime** [makehumancommunity/makehuman#16]
It should be possible to make a good approximation of a real person using measurements made with a  cloth tape-measure.  

A reasonably complete diagram of measurements used in tailoring is can be [found in seamly2d](https://github.com/FashionFreedom/Seamly2D/blob/develop/share/measurement-body-diagram.svg) (see image below for an excerpt).

These measurements are quite different to the modeling values used in MakeHuman where changes in the shape of the body are made in broad and smooth sections in a more orthogonal way.

However, it would be possible to convert between them if you could make the correct measurements from the virtual model, and then using something like scipy.optimize.minimize() you iterated across the many dimensions of the modeling parameters to find the best fit to the measurements of the real person.  

This would be useful for avatars that were interchangeable with real people for live action, or for garment design.

![image](https://user-images.githubusercontent.com/677254/45254804-226ece00-b376-11e8-803a-106b6b058a34.png)

**Comment by benkebab** [comment]
Hello, 
I'm interested in the very same subject. I find the measure tab from Makehuman a bit disturbing, since the little dotted lines doesn't seem to show the actual way that body measures are taken with a tape measure.

**Comment by Aranuvir** [comment]
This with discussed multiple times in our various bug trackers and the forum. I don't think this will come in the near future.
