### ISSUE TITLE
How can I mark the body part in makehuman?

### ISSUE THREAD

**Issue by poincarelee** [makehumancommunity/makehuman#171]
Sorry this is not a bug problem, but seems no answer for this.
I have been studying makehuman these days。 Now I would like to mark the body parts in makehuman, such as foot, hand and so on, and I also want these markers shown in makehuman interface, furthermore, these markers needs to be exported with the model simultaneously. How could I make it? Thanks a lot.

**Comment by Aranuvir** [comment]
We've a forum these topics.
