### ISSUE TITLE
No X-ray view on Linux

### ISSUE THREAD

**Issue by SuperUserNameMan** [makehumancommunity/makehuman#172]
Hello,

**Issue :** The X-ray view of the Pose/Animate tab is opaque. Can't see bones inside.

edit : same issue if i disable shaders into Settings.

-----

- **OS** : Linux Mint 20.2 x64
- **GPU** : AMD radeon R4 
- **MakeHuman version string** : 1.2.0 final (UNKNOWN:UNKNOWN) 
- **MakeHuman download origin** : official PPA
- **OpenGL driver version** :
````
OpenGL vendor string: AMD
OpenGL renderer string: AMD KABINI (DRM 2.50.0, 5.4.0-80-generic, LLVM 12.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 21.0.3
OpenGL core profile shading language version string: 4.50
````

--------

X-ray is not transparent :

![image](https://user-images.githubusercontent.com/9801802/128693866-2678cb21-f8eb-46e2-a6cf-92b4cea6412b.png)

**Comment by SuperUserNameMan** [comment]
And here are the logs : 

- [makehuman.log](https://github.com/makehumancommunity/makehuman/files/6954090/makehuman.log)
- [makehuman-debug.txt](https://github.com/makehumancommunity/makehuman/files/6954091/makehuman-debug.txt)

**Comment by black-punkduck** [comment]
Looks like error #29

try to call makehuman with options

--noshaders --nomultisampling

**Comment by SuperUserNameMan** [comment]
Yep, you are correct.

However, `--nomultisampling` alone solve the issue.

**Comment by black-punkduck** [comment]
k then it can be closed. The other one might be closed as well. I dunno if we will have a better solution somewhen
