### ISSUE TITLE
create human model from python.

### ISSUE THREAD

**Issue by LinlyAC** [makehumancommunity/makehuman#175]
Very nice work.

I'm a novice of this software.
I want to know how to create a 3D human model with a programming language (for example, python) instead of operating in a visual interface.

Thank you very much.

**Comment by SubhenduMishra29** [comment]
makehuman interface is much easier you can go through the codes for more

**Comment by joepal1976** [comment]
As it is not obvious what it is you want to achieve in detail, it's hard to give you an answer. 

If you can live with having MakeHuman running in the background, your easiest option is to write a plugin for makehuman. That way you can use all of MakeHuman's internals for generating and working with models. 

You can take a look at https://github.com/makehumancommunity/community-plugins-massproduce for an example of how such an addon looks.

Closing this issue as the issue tracker is intended for bug reports. Please use the forums at http://www.makehumancommunity.org/forum/ for generel discussions and tech support.
