### ISSUE TITLE
Windows install documentation

### ISSUE THREAD

**Issue by LyleSY** [makehumancommunity/makehuman#177]
I like the new 1.2.0 Windows installer, but please update the documentation http://www.makehumancommunity.org/wiki/Documentation:Installing_MakeHuman#Windows to reflect its existence. It would also be wonderful to document command line options for mass deployment.

**Comment by Aranuvir** [comment]
Rob would you mind to take a look at the documentation? Do we need further clarification for Windows users?

**Comment by rwbaer** [comment]
I have updated  the Wiki as requested.   I mainly focused on the Windows section, but I also updated the first section and added some comments relative to Blender 2.83 and beyond plugins.  I tried to refer to Joel's MakeHuman-Community page as much as possible.

The Wiki "running from source" seems a little dated as well.
