### ISSUE TITLE
Bones not connected

### ISSUE THREAD

**Issue by dbrown7080** [makehumancommunity/makehuman#189]
I'm having problems with not all bones not being connected., when imported into Blender.

**Comment by Aranuvir** [comment]
To be honest, I do not think this kind of bug report meets any minimal requirement to be useful. 

Depending on the type of rig, disconnected bones might rather be a feature than a bug (however plenty more information is needed).

Suggesting to reject the issue to the other Devs!

**Comment by Aranuvir** [comment]
No further info here, closing...

**Comment by dbrown7080** [comment]
I can't believe you think so little of peoples inquiries to say that they are not useful, without looking at the problem and then close the thread in that short of time. The one that I was referring to was the "game engine" armature. It is parented but the bones are disconnected. I don't see how that is a feature. This is what is exported with "default", or "default no toes"
![image](https://user-images.githubusercontent.com/101479892/174900938-e2481dfd-9665-48a4-8bc6-ae49a6b1a96b.png)
