### ISSUE TITLE
.dae to .urdf conversion for gazebo

### ISSUE THREAD

**Issue by Yeshasvitvs** [makehumancommunity/makehuman#19]
Is there any support to generate gazebo urdf files directly ?
I tried to use [collada_urdf](https://github.com/ros/collada_urdf) package but I am receiving model parsed error. 

After a bit of debugging I noticed that the [scene count](https://github.com/ros/collada_urdf/blob/923c5d33bd245e82134e8ae02e4c9d379e80eb27/collada_parser/src/collada_parser.cpp#L480) is zero and eventually the `.dae` file is not parsed correctly.

**Comment by Aranuvir** [comment]
> Is there any support to generate gazebo urdf files directly ?
Sorry, but no. Currently we haven't enough coders to implement new exporters. And honestly, I think there are enough users to prioritize that kind of exporter.
Obviously there are some glitches with our collada output, but not in the scene section, though I'm not a expert on that topic.

**Comment by joepal1976** [comment]
I never heard about the urdf format. I don't think any of the devs have worked with it. 

Thus it is unlikely this would be implemented right now, unless someone else steps in and starts to work with it.

**Comment by Aranuvir** [comment]
I don't think someone will be able to implement something like that in the foreseeable future.
