### ISSUE TITLE
Is there a possibility for makehuman to go on pypi?

### ISSUE THREAD

**Issue by cadop** [makehumancommunity/makehuman#191]
I was hoping to use makehuman in a project that would need it to be installable through pypi.  Was this tried before and determined not possible?

**Comment by joepal1976** [comment]
No, this is not something we've considered. I guess it might be technically possible, it's just that no-one saw the need. 

There might be some challenges with the assets and with the size.

**Comment by cadop** [comment]
I see, if I can find a way to get it to work would the community manage the pypi upload?

**Comment by cadop** [comment]
@Aranuvir  Can you respond to the question?
