### ISSUE TITLE
Script error with saveModel

### ISSUE THREAD

**Issue by LeHibou2** [makehumancommunity/makehuman#192]
Hello,
When executing that script in the panel on a fresh install:
`MHScript.saveModel('myTestModel')`
an error shows:
`save takes 2 positional arguments but 3 were given`

Any idea?

**Comment by Aranuvir** [comment]
There was a bug in the scripting class. Should be fixed. If anyone could test...

**Comment by joepal1976** [comment]
Thanks @Aranuvir. I have tested and confirm that it crashed before updating to master, but seems to work after pulling home latest master.
