### ISSUE TITLE
Blank black main window on Ubuntu v22.04

### ISSUE THREAD

**Issue by kshepherd2013** [makehumancommunity/makehuman#198]
(Fix already submitted as pull request) 
After upgrading to Ubuntu v22.04, I tried to run makehuman release version, and also nightly build.
In both cases the main opengl window widget is blank and black.
I fixed this by upgrading QGLWidget to QOpenGLWidget in the code.
It is now working well, and I have been using it normally for several days.
Qt deprecated QGLWidget in Dec 2014, v5.4 which is why I tried this change.

**Comment by rwbaer** [comment]
The view tab now handles z-clipping as expeced. I think this can be closed
