### ISSUE TITLE
Decide about splash screen on top / remove nudity warning

### ISSUE THREAD

**Issue by Aranuvir** [makehumancommunity/makehuman#2]
There were multiple requests in the forum to remove the always on top splash screen. This was apparently introduced to avoid issues with the nudity warning on windows platforms. The splash screen  not always on top is the current state on my branch, which recently became the current state on master, too, with the option to change the behaviour via command line option. This is probably not very convenient to the very most of our users. 

Suggestion: remove the nudity warning.

**Comment by joepal1976** [comment]
I've removed the nudity warning in ccd2a1a717619b91b7773398b0c5894a983a6624, but we should still decide upon the modality of the splash screen.

**Comment by raziel2001au** [comment]
Also, that warning caused big issues on the Mac build... if memory serves it took the rest of the app down with it when the dialog got closed :).
