### ISSUE TITLE
On Windows, fails silently if registry key-value "...\User Shell Folders\Personal" is missing

### ISSUE THREAD

**Issue by zmic** [makehumancommunity/makehuman#203]
For whatever reason, "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders\Personal" was missing on my system which causes getpath.getHomePath() to throw error. 

So double-clicking the desktop icon just did nothing which was very confusing for first-time user me.

The value defaults to "%USERPROFILE%\Documents" so changing getpath.py like this fixed it for me:

```
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, keyname) as k:
            try:
                value, type_ = winreg.QueryValueEx(k, 'Personal')
            except FileNotFoundError:
                value, type_ = "%USERPROFILE%\Documents", winreg.REG_EXPAND_SZ
```

**Comment by joepal1976** [comment]
Thanks. Having a fallback seems like an obviously good thing to have. I have added it to master now, so it should appear in the next nightly build.

**Comment by zmic** [comment]
Now I notice it should be `r"%USERPROFILE%\Documents"` with the "r" in front to escape the backslash. Maybe you caught that.

**Comment by rwbaer** [comment]
FWIW, Windows supports the forward slash just fine. It is preferrable to use the forward slash for paths in a cross-platform context to avoid having to include unnecessary escape characters.

**Comment by luzpaz** [comment]
Is this still relevant ?

**Comment by Aranuvir** [comment]
@Rob: Since this code part is windows specific, I think it's the better solution using back slashes here. But in that case we need raw strings or have to escape the back slashes. 
With commit a8bc2d54ff0ac92e78ff71431b1023eda42bf482 its a raw string now.
Guess the issue can be closed.
