### ISSUE TITLE
Sexualised children

### ISSUE THREAD

**Issue by 91thu8u53rn433** [makehumancommunity/makehuman#215]
Hi, as you don't want any contact, or there isn't a way to flag an uploaded model, I'm using the bug tracker to bring to your attention 2 uploads: http://www.makehumancommunity.org/model/slavechild1.html and http://www.makehumancommunity.org/model/slavechild2.html. What is problematic about these models is that the children depicted are only covered with a cloth, just covering their genitals but with the hips exposed. This sexualises the children. Please remove these models.

**Comment by joepal1976** [comment]
Thank you for your report. Removing things that might come close to violating swedish laws is one of the very few instances where I censor an asset. I have now unpublished the assets and will perform a full review. 

I'd like a clarification though: Is your flagging here actually a request to remove any model asset that has the age slider put below 0.25, independently of how it actually looks on the screen?

Reason I ask is that the assets in questions were so cartoonishly deformed that I would not have guessed that they were intended to depict children unless they had had the word "child" in the title.

**Comment by joepal1976** [comment]
The issue has been handled.
