### ISSUE TITLE
bitbucket-stable crashes with syntax error

### ISSUE THREAD

**Issue by martinellison** [makehumancommunity/makehuman#227]
If I try the `bitbucket-stable` branch, it crashes with a syntax error:

```
.../makehuman> git switch bitbucket-stable
Switched to branch 'bitbucket-stable'
Your branch is up to date with 'origin/bitbucket-stable'.
.../makehuman> makehuman/makehuman
  File "/home/martin/extgit/makehuman/makehuman/makehuman.py", line 452
    print "\n" + getCopyrightMessage() + "\n"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

```

Also, 
```
 python --version
Python 3.11.3
```

**Comment by joepal1976** [comment]
Bitbucket-stable is the ancient python 2.7 branch which was rescued from BitBucket when they closed down mercurial. It won't run with python 3.

**Comment by martinellison** [comment]
ok thanks. Perhaps the doco could make that more clear.

My problem is that the master branch is crashing badly for  me (which is
off topic for this issue) and I was looking for a stable version.  Perhaps
there isn't one.

Regards,
Martin Ellison
(he/him)

**Comment by martinellison** [comment]
Presumably won't fix.
