### ISSUE TITLE
Can't install Mass Produce Plugin - Mac OS Monterey 12.6

### ISSUE THREAD

**Issue by sam-spears** [makehumancommunity/makehuman#230]
Have tried to install the Mass produce plugin as shown on the YouTube video (https://www.youtube.com/watch?v=jRHnJX-TdT4&t=195s) however when I drag and drop the 1_mhapi and 9_massproduce into the plugins folder it doesn't load. 

Software:
Downloaded official release of MakeHuman (http://www.makehumancommunity.org/wiki/Releases:120mac)

Hardware and Firmware:
Macbook pro
macOS Monterey version 12.6
2020 intel i5 chip

**Comment by joepal1976** [comment]
At least mhapi should already be bundled with the release binary, and I would have thought mass produce would be too. 

There should be a settings -> plugins tab where you can see what has been included in the package. Can you post a screenshot of how that looks for you?

**Comment by sam-spears** [comment]
Hello,

Apologies, I didn't realise there was an install "zipped plugin" option. I was just putting the zipped 1_mhapi and 9_massproduce into the plugins folder expecting it too load. 

It wasn't pre-bundled but I have managed to install it. Thank you for your help!
