### ISSUE TITLE
missing "community" tab in git master

### ISSUE THREAD

**Issue by Fak3** [makehumancommunity/makehuman#24]
I have installed makehuman 1.2.0 master:ebb245b2, downloaded assets from git-lfs.
In the tutorials i see a "community" tab located after "help" tab.
Was this tab removed in git master? If so, how to download community assets?

**Comment by joepal1976** [comment]
The community tab collects plugins. These come from repositories outside the main mh one, and are bundled in builds. 

When running from source, you need to pull these separately and place them in the plugins dir (or symlink to them from there. 

See:

* https://github.com/makehumancommunity/community-plugins-mhapi
* https://github.com/makehumancommunity/community-plugins-socket
* https://github.com/makehumancommunity/community-plugins-assetdownload
* https://github.com/makehumancommunity/makehuman-plugin-for-blender

**Comment by Fak3** [comment]
thanks a lot!
