### ISSUE TITLE
Bones are not visible in Skeleton view

### ISSUE THREAD

**Issue by unit73e** [makehumancommunity/makehuman#29]
Bones are not visible on Skeleton view:

![image](https://user-images.githubusercontent.com/11358308/51089285-a260d680-1762-11e9-8557-a9f8d078fb89.png)

In particular the body should be transparent.

System Information:
GPU: AMD R9 380
Driver: Mesa 18.3.1
Kernel version: 4.20.0

**Comment by Aranuvir** [comment]
Looks as if transparency is not working. Any errors in the logs? BTW which version of MakeHuman?

**Comment by unit73e** [comment]
@Aranuvir latest git commit, so 1.2.0 pre-release. I didn't see any error with debug opengl on.

Disabling multi-sampling fixes this issue but then I get another glitch were parts of the model stay transparent on other modes. Disabling both multi-sampling and shaders seems to fix every issue.

**Comment by joepal1976** [comment]
Can you check if these issues persist with current master? We've introduced some fixes. 

If the problems remain, can you see what happens if you run makehuman with --noshaders?

**Comment by geekless** [comment]
I faced the same issue.

`--noshaders` has no effect. However `--noshaders --nomultisampling` does the job.

Running the latest master commit, c28443c2af7e6b6e9367a3c6ee76f090c81796fd

**Comment by Aranuvir** [comment]
X-Ray is working on my 1.3.0 master. Guess it was fixed. Closing this quite old issue.
