### ISSUE TITLE
Custom targets reset after "rescan targets folder" clicked

### ISSUE THREAD

**Issue by Fak3** [makehumancommunity/makehuman#33]
I went to modelling->custom and applied some custom targets to the model. After this i have downloaded few new community targets, and clicked "rescan targets folder" to see them. After the rescan, all previously applied custom targets was reset to zero. It is quite frustrating, especially when many applied custom targets was previously carefully tuned.

**Comment by joepal1976** [comment]
Yeah, that sounds like bad behavior.

**Comment by Aranuvir** [comment]
Providing a fix, testing needed...

**Comment by Aranuvir** [comment]
So, it seems to be working? Closing...
