### ISSUE TITLE
Unable to start, "Exception during event onStart"

### ISSUE THREAD

**Issue by gabrielmontagne** [makehumancommunity/makehuman#37]
Hi, I'm on Windows 10 (64), running off `master` Python 3.7.1 from anaconda. All the libraries on the README installed perfectly.
All the download_assets, and compile_xx ran perfectly fine.

But the app gets stuck on the splash screen with "Exception during event onStart".
The app is stuck, nothing on the command line after the license warning and Ctrl+C, etc., does nothing.

![image](https://user-images.githubusercontent.com/95913/52670459-7c208900-2f10-11e9-8763-aee3a6e16c60.png)

I've checked on other issues but I couldn't find anything like this open or closed.

I have to say I'm running from source because the pre-compiled binaries didn't run either.

**Comment by gabrielmontagne** [comment]
I found the argument flags in the source;: `--noshaders` ran--the thing started and seems to be working fine.

`--debugopengl` does nothing.  The thing doesn't start.

**Comment by Aranuvir** [comment]
Can you rerun MakeHuman with shaders and provide the python_err.txt file. Though, probably it's an OpenGL problem. We are aware of it, but refactoring the GL-code will probably end up in a prolonged messy task...

**Comment by gabrielmontagne** [comment]
Hi, thanks for looking into this.  I hadn't seen those error logs.

Here is the full file,
[python_err.txt](https://github.com/makehumancommunity/makehuman/files/2858013/python_err.txt)

...the exception being, 

```
Exception during event onStart
Traceback (most recent call last):
  File "./core\events3d.py", line 211, in callEvent
    method(event)
  File "./core\mhmain.py", line 848, in onStart
    self.startupSequence()
  File "./core\mhmain.py", line 772, in startupSequence
    self.loadHuman()
  File "./core\mhmain.py", line 409, in loadHuman
    self.selectedHuman = self.addObject(human.Human(files3d.loadMesh(mh.getSysDataPath("3dobjs/base.obj"), maxFaces = 5)))
  File "./apps\human.py", line 88, in __init__
    self.material = material.fromFile(getSysDataPath('skins/default.mhmat'))
  File "./shared\material.py", line 1408, in fromFile
    mat.fromFile(filename)
  File "./shared\material.py", line 488, in fromFile
    self.configureShading(diffuse=shaderConfig_diffuse, bump=shaderConfig_bump, normal=shaderConfig_normal, displacement=shaderConfig_displacement, spec=shaderConfig_spec, vertexColors=shaderConfig_vertexColors, transparency=shaderConfig_transparency, ambientOcclusion=shaderConfig_ambientOcclusion)
  File "./shared\material.py", line 949, in configureShading
    self._updateShaderConfig()
  File "./shared\material.py", line 986, in _updateShaderConfig
    bump = self._shaderConfig['bump'] and self.supportsBump()
  File "./shared\material.py", line 881, in supportsBump
    if self.shaderObj and result:
  File "./shared\material.py", line 1046, in shaderObj
    return self.getShaderObj()
  File "./shared\material.py", line 1042, in getShaderObj
    return shader.getShader(shaderPath, self.shaderDefines)
  File "./lib\shader.py", line 529, in getShader
    shader = Shader(path, defines)
  File "./lib\shader.py", line 319, in __init__
    self.initShader()
  File "./lib\shader.py", line 446, in initShader
    self.updateUniforms()
  File "./lib\shader.py", line 469, in updateUniforms
    for uniform in self.getUniforms():
  File "./lib\shader.py", line 459, in getUniforms
    uniform = VectorUniform(self.shaderId, index, name, type)
  File "./lib\shader.py", line 123, in __init__
    super(VectorUniform, self).__init__(pgm, index, name, pytype, dims)
  File "./lib\shader.py", line 60, in __init__
    self.location = glGetUniformLocation(self.pgm, name)
  File "C:\Users\gabriel\Anaconda3\lib\site-packages\OpenGL\latebind.py", line 61, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
  File "C:\Users\gabriel\Anaconda3\lib\site-packages\OpenGL\GL\VERSION\GL_2_0.py", line 383, in glGetUniformLocation
    raise ValueError( """Non-null name required""" )
ValueError: Non-null name required
```

**Comment by Aranuvir** [comment]
> GL.VENDOR: Intel
> GL.RENDERER: Intel(R) Iris(R) Graphics 550

Currently it seems your are rendering from your Intel GPU and not from your Quadro. Can you try

A) to install Intel's own graphics drivers for your iGPU, if you are not doing already, and recheck.
B) to force the usage of your Quadro for MakeHuman

C) out of curiosity try the mhtestap: https://github.com/makehumancommunity/mhtestapp

**Comment by gabrielmontagne** [comment]
Thanks, yes! This is on a new tablet so the "mode" was set to save energy.  I switched to "3D modeling" mode which forces the Quadro to kick in and the app started fine 🎉  

I'll run the test app anyway, just to see.

**Comment by gabrielmontagne** [comment]
The test app works fine, both with the Quadro and with the Intel integrated chip.
All tests look as expected, no crashes, all good.

**Comment by Aranuvir** [comment]
Well, good to heat we solved your particular problem, but bad to hear the code refuses to run on newer iGPUs and Windows 10. We probably have many users with only an iGPU and no dGPU in there system.

Closing this issue anyway. It's a known one. We will probably sooner rather than later have to rewrite the GL code.

**Comment by sombatk** [comment]
For me, running this 1.2 alpha 3 version on windows 10, I have to set my nvidia card as following:
Adjust image setting with preview --> use the advanced 3d image setting

**Comment by AssetDK** [comment]
I have the same issue here, and I don't understand much of what you are saying about this. 

But never the less, **I solved it** by running with the graphics processor. You can do that in WIN10, by right-click on the startup Icon and select the graphics processor run option (don't know what its called in English).  

I suspect that this was triggered either because I started version 1.1.1, or because my computer changes when I am not running on the monitor - I will check that when I get it back on.)

**Comment by AssetDK** [comment]
I have the same issue here, and I don't understand much of what you are saying about this. 

But never the less, I solved it by running with the graphics processor. You can do that in WIN10, by right-click on the startup Icon and select the graphics processor run option (don't know what its called in English).  
This happend because my computer changes, to run on the internal GPU, when I am not running on the monitor ...
