### ISSUE TITLE
Current git version: Geometries not shown

### ISSUE THREAD

**Issue by porky11** [makehumancommunity/makehuman#39]
I tried to add geometries (eyes, eyebrows, teeth, etc.) to my human, but it didn't work. I use the most recent version.

**Comment by rwbaer** [comment]
Help issues belong on the forum.  This space is for identified code issues.  Sounds like maybe you need to run download assets.  Feel free to repost on the forum.

**Comment by porky11** [comment]
I thought it's a bug, else I wouldn't have written it here. I'm not sure, what the reason was, but at least it works now again.
