### ISSUE TITLE
ubuntu 16.04 startup openGL error

### ISSUE THREAD

**Issue by rwbaer** [makehumancommunity/makehuman#4]
Although this started fine on Windows 10 for me, I experienced an openGL error on startup when trying it under Ubuntu 16.04 Linux .  Do we learn anything from the fact that the exception follows:
"Shader: adding built-in uniform b'gl_NormalMatrix'" ??

On Windows the lines following this in the log are:
"
[2017-07-12 16:43:38,135] log.py->message():134 -- MESSAGE -- Loaded vertex weights MakeHuman weights from file c:/MHPY3-community/makehuman/makehuman/data/rigs/default_weights.mhw
[2017-07-12 16:43:38,513] log.py->message():134 -- MESSAGE -- Loading scene
"

Here is the console messages:

```
(python34) rwbaer@Aspire:~/mhpy3-community/makehuman/makehuman$ python makehuman.py
MakeHuman Copyright (C) 2001-2017 http://www.makehuman.org
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions. For details use the option --license

NO VERSION file detected, retrieving revision info from HG
abort: no repository found in '/home/rwbaer/mhpy3-community/makehuman' (.hg not found)!
NOTICE: Failed to get hg version number from command line: 'str' does not support the buffer interface (This is just a head's up, not a critical error)
NOTICE: Failed to get hg version number using hglib: No module named 'hglib' (This is just a head's up, not a critical error)
NOTICE: Failed to get hg parent version from dirstate file: [Errno 2] No such file or directory: '/home/rwbaer/mhpy3-community/makehuman/.hg/dirstate' (This is just a head's up, not a critical error)
NOTICE: Failed to get hg tip version from cache file: [Errno 2] No such file or directory: '/home/rwbaer/mhpy3-community/makehuman/.hg/cache/tags' (This is just a head's up, not a critical error)
Detected HG revision: r? (UNKNOWN)
Initialized logging
VERSION: 1.1.1 (r? UNKNOWN) [none found]
HG REVISION: r? (UNKNOWN) [none found]
SHORT VERSION: v1.1.1
BASEMESH VERSION: hm08
IS BUILT (FROZEN): No
IS RELEASE VERSION: No
DEFAULT ENCODING: utf-8
FILESYSTEM ENCODING: utf-8
STDOUT ENCODING: UTF-8
WORKING DIRECTORY: /home/rwbaer/mhpy3-community/makehuman/makehuman
HOME LOCATION: /home/rwbaer
PYTHON PATH: ./:./lib:./apps:./shared:./apps/gui:./core:/home/rwbaer/mhpy3-community/makehuman/makehuman:/home/rwbaer/anaconda3/envs/python34/lib/python34.zip:/home/rwbaer/anaconda3/envs/python34/lib/python3.4:/home/rwbaer/anaconda3/envs/python34/lib/python3.4/plat-linux:/home/rwbaer/anaconda3/envs/python34/lib/python3.4/lib-dynload:/home/rwbaer/anaconda3/envs/python34/lib/python3.4/site-packages:/home/rwbaer/anaconda3/envs/python34/lib/python3.4/site-packages/Sphinx-1.5.1-py3.4.egg:/home/rwbaer/anaconda3/envs/python34/lib/python3.4/site-packages/setuptools-27.2.0-py3.4.egg
DLL PATH: /home/rwbaer/anaconda3/envs/python34/bin:/home/rwbaer/anaconda3/bin:/home/rwbaer/workspace/rnaseq/tools/samtools-1.1:/home/rwbaer/workspace/rnaseq/tools/bam-readcount/bin:/home/rwbaer/workspace/rnaseq/tools/bowtie2-2.2.4:/home/rwbaer/workspace/rnaseq/tools/tophat-2.0.13.Linux_x86_64:/home/rwbaer/workspace/rnaseq/tools/STAR-STAR_2.4.0f1/source:/home/rwbaer/workspace/rnaseq/tools/cufflinks-2.2.1.Linux_x86_64:/home/rwbaer/workspace/rnaseq/tools/HTSeq-0.6.1p1/scripts:/home/rwbaer/workspace/rnaseq/R-3.1.0/bin:/home/rwbaer/workspace/rnaseq/tools/FastQC:/home/rwbaer/workspace/rnaseq/tools/picard-tools-1.124:/home/rwbaer/workspace/rnaseq/tools/samstat-1.5/src:/home/ubuntu/bin/bedtools2/bin:/home/rwbaer/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
SYS.VERSION: 3.4.5 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:47:47)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
SYS.PLATFORM: linux
SYS.EXECUTABLE: /home/rwbaer/anaconda3/envs/python34/bin/python
PLATFORM.MACHINE: x86_64
PLATFORM.PROCESSOR: x86_64
PLATFORM.UNAME.RELEASE: 4.4.0-79-generic
NUMPY.VERSION: 1.11.3
No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
USE PYSIDE INSTEAD OF PYQT: False
QT.VERSION: 4.8.7
QT.JPG_SUPPORT: not supported
QT.SVG_SUPPORT: not supported
QT.PLUGIN_PATH: /home/rwbaer/anaconda3/envs/python34/plugins:/home/rwbaer/anaconda3/envs/python34/bin
QT.PLUGIN_PATH_ENV: 
QT.CONF: NOT PRESENT
PYOPENGL.VERSION: 3.1.1a1
Failed to write GL debug info to debug dump: Can't convert 'bytes' object to str implicitly
GL.EXTENSION: GL_ARB_multisample enabled (4x samples)
Creating new texture for image data/textures/texture_notfound.png.
GL.EXTENSION: GL_ARB_texture_non_power_of_two enabled
initTexture: 256, 256, False
Setting language to english
Setting language to english
Initializing default theme first.
Theme default version 1.1.0
Loaded theme data/themes/default.mht
Using Qt system style gtk+
Loading human
Loading binary mesh data/3dobjs/base.npz.
Loading material from file data/skins/default.mhmat
Shader: adding built-in uniform b'gl_ModelViewProjectionMatrixTranspose'
Shader: adding built-in uniform b'gl_NormalMatrix'
Exception during event onStart
Traceback (most recent call last):
  File "./core/events3d.py", line 211, in callEvent
    method(event)
  File "./core/mhmain.py", line 823, in onStart
    self.startupSequence()
  File "./core/mhmain.py", line 747, in startupSequence
    self.loadHuman()
  File "./core/mhmain.py", line 388, in loadHuman
    self.selectedHuman = self.addObject(human.Human(files3d.loadMesh(mh.getSysDataPath("3dobjs/base.obj"), maxFaces = 5)))
  File "./apps/human.py", line 83, in __init__
    self.material = material.fromFile(getSysDataPath('skins/default.mhmat'))
  File "./shared/material.py", line 1372, in fromFile
    mat.fromFile(filename)
  File "./shared/material.py", line 476, in fromFile
    self.configureShading(diffuse=shaderConfig_diffuse, bump=shaderConfig_bump, normal=shaderConfig_normal, displacement=shaderConfig_displacement, spec=shaderConfig_spec, vertexColors=shaderConfig_vertexColors, transparency=shaderConfig_transparency, ambientOcclusion=shaderConfig_ambientOcclusion)
  File "./shared/material.py", line 913, in configureShading
    self._updateShaderConfig()
  File "./shared/material.py", line 950, in _updateShaderConfig
    bump = self._shaderConfig['bump'] and self.supportsBump()
  File "./shared/material.py", line 845, in supportsBump
    if self.shaderObj and result:
  File "./shared/material.py", line 1010, in shaderObj
    return self.getShaderObj()
  File "./shared/material.py", line 1006, in getShaderObj
    return shader.getShader(shaderPath, self.shaderDefines)
  File "./lib/shader.py", line 522, in getShader
    shader = Shader(path, defines)
  File "./lib/shader.py", line 313, in __init__
    self.initShader()
  File "./lib/shader.py", line 440, in initShader
    self.updateUniforms()
  File "./lib/shader.py", line 462, in updateUniforms
    for uniform in self.getUniforms():
  File "./lib/shader.py", line 456, in getUniforms
    uniform.update(self.shaderId)
  File "./lib/shader.py", line 137, in update
    self.glquery(pgm, self.index, values)
  File "/home/rwbaer/anaconda3/envs/python34/lib/python3.4/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/home/rwbaer/anaconda3/envs/python34/lib/python3.4/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glGetUniformfv,
	cArguments = (1, 3, array([ 0.], dtype=float32))
)

```
**EDIT**:   When started with the --noshaders flag, startup is successful.  Skin materials appear as expected in MH viewport.

**Comment by Aranuvir** [comment]
I consider this bug fixed.

**Comment by green-green-avk** [comment]
Sorry, but the problem exists in both: the current stable and master branches... Please, provide the link to the commit which fixed it before.

**Comment by green-green-avk** [comment]
Um... Do you know guys, that index used by glGetActiveUniform() does not equal to the location used by glUniform...()? Please, fix lib/shader.py to get rid of this embarrassment.

**Comment by green-green-avk** [comment]
To be exact:

diff -r 04eb677d1568 makehuman/lib/shader.py
--- a/makehuman/lib/shader.py	Wed Mar 07 20:26:47 2018 +0100
+++ b/makehuman/lib/shader.py	Sun Nov 03 13:39:09 2019 -0800
@@ -45,8 +45,9 @@
 from core import G
 
 class Uniform(object):
-    def __init__(self, index, name, pytype, dims):
+    def __init__(self, index, location, name, pytype, dims):
         self.index = index
+        self.location = location
         self.name = name
         self.pytype = pytype
         self.dims = dims
@@ -111,9 +112,9 @@
             cls.uniformTypes2.clear()
         return type in cls.uniformTypes
 
-    def __init__(self, index, name, type):
+    def __init__(self, index, location, name, type):
         dims, dtype, pytype, glfunc, glquery = self.uniformTypes[type]
-        super(VectorUniform, self).__init__(index, name, pytype, dims)
+        super(VectorUniform, self).__init__(index, location, name, pytype, dims)
         self.type = type
         self.dtype = dtype
         self.glfunc = glfunc
@@ -125,13 +126,19 @@
             return
         values = np.asarray(data, dtype=self.dtype).reshape(self.dims)
         if len(self.dims) > 1:
-            self.glfunc(self.index, 1, GL_TRUE, values)
+            self.glfunc(self.location, 1, GL_TRUE, values)
         else:
-            self.glfunc(self.index, len(values)/self.dims[0], values)
+            try:
+              self.glfunc(self.location, len(values)/self.dims[0], values)
+            except GLerror as err:
+              log.error("%s", err.description)
 
     def update(self, pgm):
         values = np.zeros(self.dims, dtype=self.dtype)
-        self.glquery(pgm, self.index, values)
+        try:
+          self.glquery(pgm, self.location, values)
+        except GLerror as err:
+          log.error("%s", err.description)
         if len(self.dims) > 1:
             values = values.T
         self.values = values
@@ -223,9 +230,9 @@
             cls.textureTargets2.clear()
         return type in cls.textureTargets
 
-    def __init__(self, index, name, type):
+    def __init__(self, index, location, name, type):
         target = self.textureTargets[type]
-        super(SamplerUniform, self).__init__(index, name, str, (1,))
+        super(SamplerUniform, self).__init__(index, location, name, str, (1,))
         self.target = target
 
     def set(self, data):
@@ -243,7 +250,10 @@
                 glBindTexture(self.target, 0)
             else:
                 glBindTexture(self.target, tex.textureId)
-        glUniform1i(self.index, cls.currentSampler)
+        try:
+          glUniform1i(self.location, cls.currentSampler)
+        except GLerror as err:
+          log.error("%s", err.description)
         cls.currentSampler += 1
 
     @classmethod
@@ -438,14 +448,17 @@
             self.uniforms = []
             for index in xrange(parameterCount):
                 name, size, type = glGetActiveUniform(self.shaderId, index)
+#                log.debug("%s %d %s", name, size, type)
+                location = glGetUniformLocation(self.shaderId, name)
+#                log.debug("%d == %d", index, location)
                 if name.startswith('gl_'):
                     log.debug("Shader: adding built-in uniform %s", name)
                     self.glUniforms.append(name)
                     continue
                 if VectorUniform.check(type):
-                    uniform = VectorUniform(index, name, type)
+                    uniform = VectorUniform(index, location, name, type)
                 elif SamplerUniform.check(type):
-                    uniform = SamplerUniform(index, name, type)
+                    uniform = SamplerUniform(index, location, name, type)
                 uniform.update(self.shaderId)
                 self.uniforms.append(uniform)

**Comment by Aranuvir** [comment]
TBH there is no one who really knows coding OpenGL, atm. I tried to fix some things to keep the project alive. If you think you can fix some of the bugs, feel free to do so and make pull requests. We would appreciate any help we can get.

**Comment by green-green-avk** [comment]
Oops.
I admit, I rush to conclusions when I found your stable version (for Python 2.7) broken.
I wonder why such a critical fix was not backported to it...

( Yes, as it turned out, it was about this change:
https://github.com/makehumancommunity/makehuman/commit/e4e1ade99d54da6a05c23c49c8ace1736d4cf5f3#diff-c7214733c096719cdfc06f7c045540bf )

Please, close this issue.

**Comment by Aranuvir** [comment]
I'm pretty sure there are further OpenGL bugs. Would you mind to take a look at it. Assigning the task to you :)

**Comment by joepal1976** [comment]
> I admit, I rush to conclusions when I found your stable version (for Python 2.7) broken.
> I wonder why such a critical fix was not backported to it...

The old bitbucket code is abandoned for several reasons including:

- It is written in python 2, which reaches end of life in a few months
- It requires pyqt4 which has not been possible to download for windows for several years (since Riverside forcibly removed all traces of their binary from the net to force people to migrate to pyqt5)

There was no point trying to backport features to it when it wasn't possible to use it to build releases anyway.

**Comment by rwbaer** [comment]
I think it is safe to close and reopen newly identified openGL issues.  3+ years and 2 LT releases later :-)
