### ISSUE TITLE
Proxy.py error

### ISSUE THREAD

**Issue by osvaldlaszlo** [makehumancommunity/makehuman#40]
When I run the **compile_proxies.py** script, I receive the following error:

`Could not load proxy file data\3dobjs\base.mhclo.
Traceback (most recent call last):
File "compile_proxies.py", line 71, in compileProxy
proxy_ = proxy.loadTextProxy(human, path, type=None)
File "./shared\proxy.py", line 539, in loadTextProxy
proxy.max_pole *= 2
TypeError: unsupported operand type(s) for *=: 'NoneType' and 'int'`

Python 3.7.2150.1013

Thanks!

**Comment by black-punkduck** [comment]
Thanx for finding the error. The problem was, that not all files seem to create a max_pole attribute. Multiplying "nothing" with 2 results in the error. I simply assume 8 before. It might be changed by reading the file ...
