### ISSUE TITLE
Makehuman 1.2.0 a2 crashes on startup on Windows 10

### ISSUE THREAD

**Issue by pandenista** [makehumancommunity/makehuman#41]
I installed Makehuman 1.2.0 a2 on my notebook with Windows 10 Home 64bit (1809), Processor Intel Core i7-6700HQ, graphic card NVidia GeForce GTX 965M but when I try to run it through the default icon in Start menu, it crashes on startup: "Exception during event onStart" and no window is shown anymore (just the splash screen with the error message above, when I click on it, everything is going down). What should I do to get it ready?
Thanks, Martin.

**Comment by rwbaer** [comment]
Although reports of this type are helpful, they belong on the forum.  This venue is for identified coding problems.  Please repost on forum.

**Comment by pandenista** [comment]
I'm sorry but I can't register to your stupid registration form so I can't post it to the forum... Martin

Stáhněte si Outlook pro Android<https://aka.ms/ghei36>




On Sat, Mar 2, 2019 at 1:09 PM +0100, "Rob Baer" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #41<https://github.com/makehumancommunity/makehuman/issues/41>.

**Comment by Aranuvir** [comment]
It does not happen to be that issue: https://github.com/makehumancommunity/makehuman/issues/37 ?
