### ISSUE TITLE
White Screen unusable

### ISSUE THREAD

**Issue by Cultusfit** [makehumancommunity/makehuman#43]
Went to the newest soon to be launched version. All I get in the middle where there is usually a model was a white screen

Windows 10

AMD A12-9720P RADEON R7, 12 COMPUTE CORES 4C+8G

Thanks!

**Comment by joepal1976** [comment]
We're playing around with what is to become alpha 3. You can download it from http://download.tuxfamily.org/makehuman/nightly/a3rc.zip. Can you try that and see if it solves your problem?

**Comment by Cultusfit** [comment]
That works just fine so far!

Might get the installer to check for old versions and update because now I
have two versions lol.
But other than that seems fine. I'll play around some and see if there are
any issues and report them to the bug forum. Thank you

**Comment by joepal1976** [comment]
Closing as the original probel is already fixed.
