### ISSUE TITLE
Contents of Proxymeshes folders disappears in 1.2A3 Alpha.

### ISSUE THREAD

**Issue by AlseyWalsey** [makehumancommunity/makehuman#45]
I've been using the alphas since the beginning and making Proxy's with no problems.  I have to remove everything from the proxymeshes folder in my documents, then restart the program. I can't simply put them back in the folder after that. I have to load them one at a time. If I load a knew Toon, all of the proxymeshes disappear again, all of them. If I load a toon The Proxy is on the toon, but I cant access anything in the Proxymeshes folders. MH's or mine or downloaded ones. This just started happening today.  I've uninstalled and reinstalled the program twice.

Allan

**Comment by AlseyWalsey** [comment]
I got it working again. I deleted anything that looked like user data in documents and reinstalled the Program.

**Comment by joepal1976** [comment]
If it happens again, take a look at http://www.makehumancommunity.org/wiki/FAQ:How_to_provide_a_makehuman_log_for_a_good_bug_report%3F

For now, I'm going to close this on the assumption that something had gotten confused in the data folders.
