### ISSUE TITLE
No model preview

### ISSUE THREAD

**Issue by videlanicolas** [makehumancommunity/makehuman#49]
Program boots but no preview is available:
![Screenshot from 2019-06-02 22-49-44](https://user-images.githubusercontent.com/14795413/58761598-8c28ab00-8589-11e9-86c5-da41c599a23d.png)
I ran `makehuman-community --fullloggingopengl` and these are the logs:
```
...
libpng warning: iCCP: known incorrect sRGB profile
...
[3108:3108:0602/211744.694969:ERROR:sandbox_linux.cc(368)] InitializeSandbox() called with multiple threads in process gpu-process.
Rendering mesh rectangle_None
[3070:3089:0602/211744.721111:ERROR:browser_process_sub_thread.cc(217)] Waited 3 ms for network service
...
```
My set-up
- OS: Ubuntu 18.04.1 (Debian 4.18.0-20-generic).
- MakeHuman version: 1.2.0 Alpha3

**Comment by Fak3** [comment]
if you have intel gpu - there is an recently emerged issue with linux driver. That issue is reported here as #46

**Comment by videlanicolas** [comment]
should we close this bug  as duplicate then?

**Comment by Aranuvir** [comment]
I think it is a duplicate of #46. There is a bug fix, now. Could you recheck with that fix? Closing here. Please report to the other thread.
