### ISSUE TITLE
Chrome  skin

### ISSUE THREAD

**Issue by VitorDja1234** [makehumancommunity/makehuman#51]
![Captura de Tela (9)](https://user-images.githubusercontent.com/52438212/60489185-4c62f980-9cd6-11e9-9b08-eec58ac0be70.png)

The skin is chrome!

How come?

How can I fix this?

Tks!!

**Comment by joepal1976** [comment]
This is explained in the FAQ: http://www.makehumancommunity.org/wiki/FAQ:MakeHuman_renders_odd_colours_and_weird_transparency_artefacts._Can_you_help_me%3F
