### ISSUE TITLE
Revise version string for logging.

### ISSUE THREAD

**Issue by Aranuvir** [makehumancommunity/makehuman#52]
Taking a look at recent log files, there is still no suitable version string.

-> get rid of that Hg stuff...
-> create a proper version object inside MakeHuman.py (with full, short, build hash, etc), which then is hooked up to G or G.app and can be accessed from all other parts of the code...

**Comment by rwbaer** [comment]
Does the help get version string fulfill part of this need?

**Comment by joepal1976** [comment]
For testing. 

I think the above commit fixes the issue, but it remains to be seen if it also works for builds / non-source

**Comment by joepal1976** [comment]
Assuming this to be fixed.
