### ISSUE TITLE
Pose sort order is case sensitive

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/makehuman#54]
This is probably true for all filechooser views. 

To demonstrate, add a new pose called "Test", and you'll see it appears at the top of the list rather than at the bottom. 

Sorting should probably be case INsensitive in filechoosers.

**Comment by Aranuvir** [comment]
It would make sense, if the displayed names were case sensitive, too.
Provided a fix with commit 875e0c0.
Can you test?

**Comment by joepal1976** [comment]
Works fine for me, for all files I have with mixed case.

**Comment by joepal1976** [comment]
Fixed in https://github.com/makehumancommunity/makehuman/commit/875e0c05e90d1bb05481e7529c7cb3cbd996ffcf
