### ISSUE TITLE
Cannot install makehuman official

### ISSUE THREAD

**Issue by fsdoma** [makehumancommunity/makehuman#55]

**Comment by fsdoma** [comment]
Hello,
I try to install using the official PPA and get this:
sudo add-apt-repository ppa:makehuman-official/makehuman-11x
...
Err:21 http://ppa.launchpad.net/makehuman-official/makehuman-11x/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
...
Reading package lists... Done                                                  
E: The repository 'http://ppa.launchpad.net/makehuman-official/makehuman-11x/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.


sudo apt-get update
...
Err:7 http://ppa.launchpad.net/makehuman-official/makehuman-11x/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                      
E: The repository 'http://ppa.launchpad.net/makehuman-official/makehuman-11x/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

I tried to install the community version too but this has unresolved dependencies.

**Comment by Aranuvir** [comment]
This was answered here:
http://www.makehumancommunity.org/forum/viewtopic.php?f=3&t=18013#p49184
-> Rejecting...
