### ISSUE TITLE
Cannot install makehuman on Ubuntu 18.04

### ISSUE THREAD

**Issue by fsdoma** [makehumancommunity/makehuman#57]
I have to reopen this issue -  it was closed without solving it.

for the 1.2 PPA
The Instructions say:
sudo add-apt-repository ppa:makehuman-official/makehuman-community
sudo apt-get update
Doing the first I get:
Err:7 http://ppa.launchpad.net/makehuman-official/makehuman-11x/ubuntu bionic Release                                               
  404  Not Found [IP: 91.189.95.83 80]

For the 1.1 PPA
The instructions say:
Official stable releases of the 1.1.x series of MakeHuman. To enable the PPA and then install MakeHuman, run:
sudo add-apt-repository ppa:makehuman-official/makehuman-11x
sudo apt-get update
sudo apt-get install makehuman
Doing the first I get:
Err:6 http://ppa.launchpad.net/makehuman-official/makehuman-11x/ubuntu bionic Release                                  
  404  Not Found [IP: 91.189.95.83 80]
Get:7 http://cz.archive.ubuntu.com/ubuntu bionic-backports InRelease [74,6 kB]       
Reading package lists... Done                                   
E: The repository 'http://ppa.launchpad.net/makehuman-official/makehuman-11x/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

The answer I got for 1.2 was: "It should work. What is missing?" (see above)
The answer for 1.1 was: "Was not built for bionic." (I ma not a developer and do not know what this means) and "Try to install the alpha version" (... what is due to the makehuman-site 1.2. This saying I tried to install the alpha version and it failed too).

**Comment by joepal1976** [comment]
What you need to do is install from the 1.2.0 PPA. The url to this, as well as instructions, are here: https://launchpad.net/~makehuman-official/+archive/ubuntu/makehuman-community

If you still have problems with getting error messages about the makehuman-11x PPA, you should remove that PPA before trying to add the makehuman-community one. 

https://itsfoss.com/how-to-remove-or-delete-ppas-quick-tip/

**Comment by Aranuvir** [comment]
still not a bug...

**Comment by fsdoma** [comment]
Hi Joepal,

I tried to purge the 1.1 PPA.
root@frankies:~# apt-get install ppa-purge
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 makehuman-community : Depends: makehuman-community-clothes but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
root@frankies:~#

It seems I cannot install software anymore with makehuman installed.
At least we got an information which package is missing.

I removed makehuman using Synaptic with my first try last week.
apt --fix-broken doesn't bring anything neither here.

**Comment by fsdoma** [comment]
Hello
Joel, Aranuvir,

I send this here too. On the forum is a bit more information.

I found some further input.
Trying to purge the 1.1 PPA:
apt-get install ppa-purge
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
makehuman-community : Depends: makehuman-community-clothes but it is not
going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or
specify a solution).

This gives us the information that makehuman-community-clothes is the
problem candidate.

Thank you for your activity with this
Frank

**Comment by Aranuvir** [comment]
Is the problem solved, now? Can we close?

**Comment by fsdoma** [comment]
Hello,
Yes, as I mentioned on the forum: Clearing the cache and reinstall solved
the problem. Maybe to NOT hold problem packages in the cache would prevent
such type of problems. ... but this is for another forum.

Thanks again :)
Frank
