### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by thankjura** [makehumancommunity/makehuman#6]
git clone https://github.com/makehumancommunity/makehuman.git
cd makehuman
./buildscripts/build_prepare.py . ../build

`
......
[88% done] converted proxy data/3dobjs/a7_converter.proxy
All done.

Exporting files from git repo
Traceback (most recent call last):
  File "./buildscripts/build_prepare.py", line 637, in <module>
    print(export(args['sourcePath'], args['targetPath'], args.get('skiphg', False), args.get('skipscripts', False), args.get('nodownload', False)))
  File "./buildscripts/build_prepare.py", line 607, in export
    return exporter.export()
  File "./buildscripts/build_prepare.py", line 205, in export
    self.exportGITFiles()
  File "./buildscripts/build_prepare.py", line 417, in exportGITFiles
    shutil.copytree(self.sourceFile(),tf, ignore=shutil.ignore_patterns(".git",".idea","__pycache__"))
  File "/usr/lib64/python3.6/shutil.py", line 359, in copytree
    raise Error(errors)
shutil.Error: [('/home/GrandMaster/Desktop/makehuman/blendertools/makewalk/makeclothes', '/home/GrandMaster/Desktop/build/blendertools/makewalk/makeclothes', "[Errno 2] No such file or directory: '/home/GrandMaster/Desktop/makehuman/blendertools/makewalk/makeclothes'"), ('/home/GrandMaster/Desktop/makehuman/blendertools/makewalk/maketarget', '/home/GrandMaster/Desktop/build/blendertools/makewalk/maketarget', "[Errno 2] No such file or directory: '/home/GrandMaster/Desktop/makehuman/blendertools/makewalk/maketarget'")]
`

ls -la blendertools/makewalk/makeclothes
`
lrwxrwxrwx 1 jura jura 71 дек  6 23:34 blendertools/makewalk/makeclothes -> /home/stefan/PycharmProjects/Python3/makehuman/blendertools/makeclothes
`

blendertools/makewalk/makeclothes and blendertools/makewalk/maketarget is a broken link

**Comment by Aranuvir** [comment]
Thanks for posting. That's really bad, because I neither know why these symlinks were created, nor why they where committed. Should be fixed now...
