### ISSUE TITLE
makehuman don't open

### ISSUE THREAD

**Issue by marcos-teles** [makehumancommunity/makehuman#60]
Hi, I am new user of the software and, after install on windows 10, I try open and nothing happens... 
I see in my documents a file call python_err, maybe it can help to solve the problem... sorry for the english... I'm from Brasil

Initialized logging
VERSION: 1.2.0 Alpha3
HG REVISION: UNKNOWN
SHORT VERSION: alpha3
BASEMESH VERSION: hm08
IS BUILT (FROZEN): No
IS RELEASE VERSION: Yes
DEFAULT ENCODING: utf-8
FILESYSTEM ENCODING: utf-8
STDOUT ENCODING: cp1252
LOCALE PREFERRED ENCODING: cp1252
WORKING DIRECTORY: C:\Users\mtele\AppData\Local\makehuman-community\makehuman
HOME LOCATION: C:/Users/mtele/OneDrive/Documentos
PYTHON PATH: ./;./lib;./apps;./shared;./apps/gui;./core;C:\Users\mtele\AppData\Local\makehuman-community\Python\python36.zip;C:\Users\mtele\AppData\Local\makehuman-community\Python;C:\Users\mtele\AppData\Local\makehuman-community\pkgs
DLL PATH: C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Brackets\command;C:\Users\mtele\AppData\Local\Microsoft\WindowsApps;
SYS.VERSION: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)]
SYS.PLATFORM: win32
SYS.EXECUTABLE: C:\Users\mtele\AppData\Local\makehuman-community\Python\pythonw.exe
PLATFORM.MACHINE: AMD64
PLATFORM.PROCESSOR: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
PLATFORM.UNAME.RELEASE: 10
PLATFORM.WIN32_VER: 10 10.0.18362 SP0 Multiprocessor Free
NUMPY.VERSION: 1.13.3
No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
QT.VERSION: 5.10.1
QT.JPG_SUPPORT: not supported
QT.SVG_SUPPORT: not supported
QT.PLUGIN_PATH: C:/Users/mtele/AppData/Local/makehuman-community/pkgs/PyQt5/Qt/plugins;C:/Users/mtele/AppData/Local/makehuman-community/Python
QT.PLUGIN_PATH_ENV: 
QT.CONF: NOT PRESENT
PYOPENGL.VERSION: 3.1.0
Failed to write GL debug info to debug dump: GLError(
	err = 1282,
	description = b'opera\xe7\xe3o inv\xe1lida',
	baseOperation = glGetString,
	cArguments = (GL_VENDOR,)
)
Failed to write GL debug info to debug dump: GLError(
	err = 1282,
	description = b'opera\xe7\xe3o inv\xe1lida',
	baseOperation = glGetIntegerv,
	pyArgs = (
		GL_SAMPLES_ARB,
		<object object at 0x03DC3168>,
	),
	cArgs = (
		GL_SAMPLES_ARB,
		array([0], dtype=int32),
	),
	cArguments = (
		GL_SAMPLES_ARB,
		array([0], dtype=int32),
	)
)

**Comment by joepal1976** [comment]
There is a FAQ at http://www.makehumancommunity.org/wiki/FAQ:MakeHuman_does_not_start

Please check if this helps you. If not, add the extra information that is requested in the FAQ as a comment here.

**Comment by marcos-teles** [comment]
Hi! Thank you for the answer! I send the information for FAQ. I just see
the link for  the FAQ after send email for you... sorry for bother...

Em qui, 26 de set de 2019 às 07:46, Joel Palmius <notifications@github.com>
escreveu:

**Comment by Aranuvir** [comment]
We are aware of endless OpenGl issues. I consider this bug report a duplicate and will close it.
