### ISSUE TITLE
Eyeball material change does not occur.

### ISSUE THREAD

**Issue by afarlie** [makehumancommunity/makehuman#63]
http://www.makehumancommunity.org/forum/viewtopic.php?f=6&t=18153&p=49573#p49573

Affected Version: 1.1.1

Open MakeHuman,

Set an eyeball type.  

Attempt to change Eye Material type using Materials tab.

No change is visible in output.

**Comment by afarlie** [comment]
I should note this fault/behaviour is not present in 1.2,0 alpha 3

**Comment by afarlie** [comment]
in 1.1.1  It seems to be incorrectly combining  a litsphere texture with a diffuse one, or mistakenly using one when it should be using the other.

**Comment by Aranuvir** [comment]
Since Alpha3 is not affected, I consider this issue resolved.
