### ISSUE TITLE
why makehuman read my personal data

### ISSUE THREAD

**Issue by TorosFanny** [makehumancommunity/makehuman#64]
Version: 1.2.0 Alpha4 (UNKNOWN:UNKNOWN)
OS: ArchLinux

I'm new to makehuman and want to learn about it. I opened makehuman in console, and get the following message
<img width="955" alt="image" src="https://user-images.githubusercontent.com/6369146/67630071-9b9fec00-f8bc-11e9-85a9-073c4d3277e7.png">
but that is my personal data, and that has nothing to do with makehuman. My question is why makehuman read that and how to stop that.

**Comment by Aranuvir** [comment]
MakeHuman does not read your personal data. It looks like you have installed IPython, the shell plug-in makes use of it. IPython writes its global history to the log files. I haven't found a way to prevent IPython doing that, yet. If you don't like it, you can deactivate the shell plug-in.

**Comment by TorosFanny** [comment]
Ok, I got it, thank you.
