### ISSUE TITLE
Settings are loaded AFTER most things are initialized

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/makehuman#69]
It is a problem that we currently cannot define settings that aim at the graphics initialization procedure, as the settings file is loaded *after* the graphics subsystem and the UI is initialized.

For example, we'd probably want a settings checkbox corresponding to --noshaders, as well as an option for skipping some graphics settings (see for example the samples stuff which shouldn't hang on --noshaders, https://github.com/makehumancommunity/makehuman/commit/5e6f5364beda479309af2cbb3df4b36cd5260904)

As it stands, rewriting this is a bit more intrusive than I thought, so will wait with it until after alpha 4.

**Comment by Aranuvir** [comment]
Just a personal opinion: if the --noshaders option is the only reason to rewrite this part of the code, I'd prefer to get our OpenGL issues fixed. 
IMHO --noshaders is a bad workaround for our problems. At least I do not start Blender with a --noshaders option...

**Comment by joepal1976** [comment]
This is solved in principle, although a less ugly solution would have been desired.
