### ISSUE TITLE
Export to collada is broken with python 3.8

### ISSUE THREAD

**Issue by VadikLeshy** [makehumancommunity/makehuman#70]
'time.clock()' call was removed in python 3.8

But in file 'makehuman/plugins/9_export_collada/mh2collada.py' this call is used only for beautiful logs;

I removed lines

'time1 = time.clock()' ( line 69 ),

'time2 = time.clock()' ( line 166 ) and 

'log.message("Wrote Collada file in %g s: %s", time2-time1, filepath)' ( line 167 ) 

from my local installation of makehuman and it works just fine for me.

**Comment by Aranuvir** [comment]
Thanks for posting, should be fixed with the next release. We should discuss, if we need those timing tests anyway.

**Comment by Aranuvir** [comment]
I've this should be fixed. Testing needed.

**Comment by Aranuvir** [comment]
No further input here. Seems to be fixed. Closing...
