### ISSUE TITLE
Can I generate a human model with Python script?

### ISSUE THREAD

**Issue by Jerryzhangzhao** [makehumancommunity/makehuman#72]
Hi, the makahuman indeed a great work! And I wondering that if I can generate a human model using python script or windows bat process or shell, with some imput info like gender.measure in the Modelling tab?

**Comment by Aranuvir** [comment]
You can access all data via python script. Take a look at the massproduce plugin to see how that is done. For further information please make contact via our forum. As stated in the README.md we'd appreciate to handle only bug reports in the bug tracker.
