### ISSUE TITLE
Possible solution for No OpenGL_accelerate module loaded

### ISSUE THREAD

**Issue by razvanab** [makehumancommunity/makehuman#73]
I think I found out why people are getting this error "No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'" I have a discrete graphics card and the integrated one enabled to, and I think makehuman chose the integrated graphics as the default. I disable the integrated one from the device manager in windows 10 and makehuman started without problems.

Sorry for posting here but the forum page doesn't load.

**Comment by Aranuvir** [comment]
The solution is to install the package PyOpenGL-accelerate via pip. That's a hint, not a bug. 

The package is not distributed by Linux' common package management systems, at least on Debian based systems...

**Comment by razvanab** [comment]
I've installed  PyOpenGL-accelerate via pip and this still gave me that error. Disabling the integrated graphics via device manager fix the issue.

**Comment by Aranuvir** [comment]
>I've installed PyOpenGL-accelerate via pip and this still gave me that error. Disabling the integrated graphics via device manager fix the issue.
>
MH ships with its own Python interpreter. Did you install it for this interpreter?

>It will be nice to have an option to chose what GPU to use at start.
>
AFAIK this is not possible, since it is handled by the gc-driver/operating system not the application

**Comment by razvanab** [comment]
I have tested with both versions the integrated interpreter and the external one "3.7.6".

**Comment by Aranuvir** [comment]
Just to clarify: the missing OpenGL-accelerate module is not the reason for the OpenGL errors with some graphics cards. The module is not necessary.
Though it installed and loaded without problems on my Linux system.

**Comment by razvanab** [comment]
In windows 10 the problem still persists. I will disable the integrated GPU to run MH until a solution will be found.

**Comment by Aranuvir** [comment]
Again we are aware of multiple OpenGL issues, but the missing module has nothing to do with that!

**Comment by mirh** [comment]
Integrated graphics having broken opengl in windows 10 is a known bug of the intel drivers for older gpus
https://github.com/pal1000/save-legacy-intel-graphics

**Comment by bassmaji** [comment]
Thanks Aranuvir, your solution worked well with me!
