### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by aspadm** [makehumancommunity/makehuman#79]
I encountered untranslated in Russian elements of the interface. While dealing with localization, I found the `data/languages` folder. It seems that all translated strings are taken from the `russian_generiс.json` file, and all available for translation from `master.json`.

However, some of the lines (for example, `Forehead bulge`) are missing from the list of available ones, being mentioned only in files from the `data/modifiers` folder.

Will localization support for such parameters be added?

**Comment by aspadm** [comment]
OK, after some research I found a method `dumpMissingStrings` in file `makehuman/lib/language.py`.
Looks like it's not used anywhere, so I just called it inside method `onQuit` of `mhmain`.
Maybe I find a better way to collect all the strings to translate.

**Comment by joepal1976** [comment]
As you have noted, we're severely behind on translations. The current translations were made for 1.1.0 (I think). 

Translations are done via transifex at https://www.transifex.com/makehuman/makehuman/, but since a lot of original strings are missing there too, it doesn't help the current situation.

**Comment by Aranuvir** [comment]
The dumpMissingStrings function is called  by the onStop event four lines above the onQuit event :)

Perhaps we should reopen this issue and generalize it a bit since we must rework all translations anyway.

**Comment by aspadm** [comment]
> Perhaps we should reopen this issue and generalize it a bit since we must rework all translations anyway.
Currently, I work on translation. There are several places, where strings are not translatable, so there are needings in fix several places in code too.
Some strings that are already translated should not be translated (example: names of bones).
