### ISSUE TITLE
Setting Rig with Python Command

### ISSUE THREAD

**Issue by wutayng** [makehumancommunity/makehuman#81]
I am attempting to load a rig onto a human with a python command. The following seems to work:
```
cmu_skel = skeleton.load(/path/to/cmu_mb.mhskel, G.app.selectedHuman.meshData)
G.app.selectedHuman.setSkeleton(cmu_skel)
```
First, I noticed the GUI for the 'Skeleton' tab is not the same when this command is executed vs. when 'Cmu mb' is simply clicked on the right under 'Rig presets'. The following pictures show 1: the GUI when the command above is executed, and 2: the GUI when 'Cmu mb' is clicked.

![python_setskeleton](https://user-images.githubusercontent.com/11264840/75095124-787a0600-5557-11ea-96bb-0747913c7275.png)
![clicked_rig](https://user-images.githubusercontent.com/11264840/75095127-8039aa80-5557-11ea-8a6e-bd03b1b063b3.png)

This difference has propagated an error to blender when I attempt to load & retarget a cmu mocap .bvh file. The following pictures show 1: the imported mhx2 human with cmu mocap .bvh when skeleton is set using the command above. Notice the large deformation coming out of the hands and the incorrect placement of the eyeballs. And 2: the imported mhx2 human with the same cmu mocap .bvh when the skeleton is set via clicking (vs. python command).

![blender_code_rig](https://user-images.githubusercontent.com/11264840/75095179-fdfdb600-5557-11ea-8195-aada292df20b.png)
![blender_clicked_rig](https://user-images.githubusercontent.com/11264840/75095180-ffc77980-5557-11ea-8b9d-4c8938f78dfc.png)

I have not been able to find alternative methods for setting a rig via python as this method seems to be designed for that exact purpose.

**Comment by Aranuvir** [comment]
ad 1): It's the GUI that triggers the load function, not the load function that alters the GUI!
ad 2): I'm not so deep in that matter, but I assume you're missing some weighting stuff. Perhaps you want to investigate  skeletonlibrary.py for further information. Probably not a bug, since it works from GUI...
