### ISSUE TITLE
Screen shot appearance

### ISSUE THREAD

**Issue by brcisna** [makehumancommunity/makehuman#83]
hello All,

makehuman-community.1.2.x from source
Debian Bullseye (11)

Backstory, Moved from Debian Buster (10) to Debian Bullseye (11).( Have used the LTSP package with Debian for many years which means a server provides an squash image to clients on the network that have no hard disk.)

Problem. On the diskless workstation when launching makehuman the viewport appears to be a screen shot,of desktop,,albiet kind of a scrambled pattern . For the same user logging into server and running makehuman everything appears as normal.
This same workstation worked fine with Debian Buster,,previous version. The machine is a pretty nice Dell All-in One with Intel HD graphics so i think the opengl requirement should; be met in the readme.

Thank You

**Comment by Aranuvir** [comment]
From your description I think it is this issue: #46?

**Comment by Aranuvir** [comment]
There has not been further input. Closing since it seems to be a duplicate.
