### ISSUE TITLE
export fbx with helper geometry results in wrong gender

### ISSUE THREAD

**Issue by goddamnmaddog** [makehumancommunity/makehuman#87]
MAKEHUMAN ver 1.2.0

Minimal setup reproducing error:

I create character.
I only change gender to female for test.

Export:
as fbx (with feet on ground, Binary FBX, Helper geometry)

When import into blender, the error is visible. The character is modeled right, but has wrong gender.

All settings, textures are correct, helper geometry is there. The character looks like in makehuman. Topology is right. But also there is a penis.

**Comment by Aranuvir** [comment]
The helper mesh does not have a gender, so you will always get what you see. And it will look always (more or less) the same, regardless the way you bring a model with helpers to Blender (except MPFB and MHX2 will also create a basic material setup for convenience). The purpose of the helpers is basically supporting the cloth creation and unnecessary parts can get deleted anyway.  We won't fix that.

BTW, as a side node, when I exported a full equipped model, the helpers did not show up. That's currently not the behavior I would have expected. Further investigation is needed. But this should go a separate ticket then...
