### ISSUE TITLE
Column Sort Order

### ISSUE THREAD

**Issue by jwcape** [makehumancommunity/makehuman#88]
For the Download assets window, sorting by node id seems to be in alphabetic order,
not numeric order.
See the attached example for clothing, displayed with a descending node id sort.

This was observed with MakeHuman version 1.2.0 Alpha4 (UNKNOWN:UNKNOWN)
running on macOS Catalina 10.15.4

![image](https://user-images.githubusercontent.com/24942939/81882732-4c639500-9548-11ea-8c6e-b92bc481d751.png)

**Comment by joepal1976** [comment]
This is probably true for beta 1 too. I don't think anyone poked at this in between.

**Comment by joepal1976** [comment]
Moving to the assetdownloader issue tracker, https://github.com/makehumancommunity/community-plugins-assetdownload/issues/29
