### ISSUE TITLE
Theme numbering

### ISSUE THREAD

**Issue by rwbaer** [makehumancommunity/makehuman#92]
The text flying by on the startup screen suggests that we have a theme tagged as 1.1.0.  Do we want any theme adjustments for 1.2.0?  If so, now is the time I guess.  If not, we may still want to set the theme version to the same number as a release version.

1.2.0 Beta1 (master:936826d2)1.2.0 Beta1 (master:936826d2)

**Comment by joepal1976** [comment]
Renamed to 1.2.0 now.
